# Site settings
title: Let today be the start of something new!
header-img: img/home-bg.png
email: barbara.m.washington@gmail.com
copyright_name: SilverBright
description: > # this means to ignore newlines until "baseurl:"
  New Beginnings...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  SilverBright
learn_profile: SilverBright
email_username: barbara.m.washington@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
